name: Flutter Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release APKs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true
      
      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      
      - name: Get dependencies
        run: flutter pub get

      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          cat > android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=${{ github.workspace }}/android/app/upload-keystore.jks
          EOF

      - name: Set versionName and versionCode
        id: version
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          VERSION_NAME=${TAG_NAME#v}
          
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION_NAME"
          MAJOR="${VERSION_PARTS[0]:-0}"
          MINOR="${VERSION_PARTS[1]:-0}"
          PATCH="${VERSION_PARTS[2]:-0}"
          BUILD_NUMBER=$((MAJOR * 10000 + MINOR * 100 + PATCH))
          
          
          echo "versionName=$VERSION_NAME" >> $GITHUB_ENV
          echo "versionCode=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Update pubspec.yaml version
        run: |
          yq e -i ".version = env(versionName) + \"+\" + env(versionCode)" pubspec.yaml

      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi
      
      - name: Build Universal APK
        run: flutter build apk --release
      
      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release
      
      - name: Rename APK files
        run: |
          # Rename APKs
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/DayFlow-v${{ env.versionName }}-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/DayFlow-v${{ env.versionName }}-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/DayFlow-v${{ env.versionName }}-x86_64.apk
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/DayFlow-v${{ env.versionName }}-universal.apk
          # Rename AAB
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/DayFlow-v${{ env.versionName }}.aab
      
      - name: Calculate SHA256
        run: |
          cd build/app/outputs
          echo "### SHA256 Checksums" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          find . -name "*.apk" -o -name "*.aab" | xargs sha256sum | tee checksums.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          mv checksums.txt flutter-apk/
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/flutter-apk/checksums.txt
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          name: DayFlow ${{ env.versionName }}
          body: |
          generateReleaseNotes: true
          makeLatest: true
          prerelease: false